#!/bin/bash 
sudo apt update && sudo apt upgrade -

sudo apt-get install git-all -y
sudo apt-get install curl -y
sudo su

sudo apt update

sudo apt install libfuse2

sudo apt install fuse

wget https://github.com/OwshenNetwork/owshen/releases/download/v0.1.0/Owshen_v0.1.0_x86_64.AppImage

chmod +x Owshen_v0.1.0_x86_64.AppImage 
 
./Owshen_v0.1.0_x86_64.AppImage init

./Owshen_v0.1.0_x86_64.AppImage info

./Owshen_v0.1.0_x86_64.AppImage wallet
